# Generated by Django 4.1 on 2022-08-30 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dis_user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dis_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tb_modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_name', models.CharField(max_length=155)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mod_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_discipline', to='disciplines.tb_disciplines')),
            ],
        ),
        migrations.CreateModel(
            name='tb_dis_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipine', to='disciplines.tb_disciplines')),
                ('dis_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tb_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla_name', models.CharField(max_length=255)),
                ('cla_videourl', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cla_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cla_module', to='disciplines.tb_modules')),
            ],
        ),
    ]
