# Generated by Django 4.1 on 2022-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_class',
            name='cla_module',
        ),
        migrations.AddField(
            model_name='tb_modules',
            name='mod_classes',
            field=models.ManyToManyField(related_name='mod_class', to='disciplines.tb_class'),
        ),
    ]
