# Generated by Django 4.1.2 on 2023-09-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='school_grade',
        ),
    ]
